services:
  postgres:
    container_name: travel-with-anna-postgres
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: travel_with_anna
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      SERVICE_TAGS: prod
      SERVICE_NAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - twa-network
    restart: unless-stopped

  backend:
    container_name: travel-with-anna-backend
    build:
      context: ./backend/travel-with-anna
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/travel_with_anna
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USER}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SERVICE_TAGS: prod
      SERVICE_NAME: app
    depends_on:
      - postgres
    networks:
      - twa-network
    restart: unless-stopped

  frontend:
    container_name: travel-with-anna-frontend
    build:
      context: ./frontend/travel-with-anna-ui
      dockerfile: Dockerfile`
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - twa-network
    restart: unless-stopped

networks:
  twa-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
