services:
  postgres:
    container_name: travel-with-anna-postgres
    restart: unless-stopped
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: travel_with_anna
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      SERVICE_TAGS: prod
      SERVICE_NAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - twa-network


  backend:
    container_name: travel-with-anna-backend
    build:
      context: ./backend/travel-with-anna
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/travel_with_anna
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_MAIL_HOST: sandbox.smtp.mailtrap.io
      SPRING_MAIL_PORT: 2525
      SPRING_MAIL_USERNAME: ${MAILTRAP_USER}
      SPRING_MAIL_PASSWORD: ${MAILTRAP_PASSWORD}
      SPRING_MAIL_PROPERTIES_AUTH: 'true'
      SPRING_MAIL_PROPERTIES_STARTTLS_ENABLE: 'true'
      SPRING_MAIL_PROPERTIES_SSL_TRUST: smtp.mailtrap.io
      SERVICE_TAGS: prod
      SERVICE_NAME: app
    depends_on:
      - postgres
      - mailtrap
    networks:
      - twa-network
    restart: unless-stopped

  mailtrap:
    container_name: travel-with-anna-mailtrap
    restart: unless-stopped
    image: eaudeweb/mailtrap
    ports:
      - "2525:2525"
    expose:
      - "2525"
    networks:
      - twa-network

  frontend:
    container_name: travel-with-anna-frontend
    restart: unless-stopped
    build:
      context: ./frontend/travel-with-anna-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - twa-network

networks:
  twa-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
