spring:

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE}
      minimum-idle: ${HIKARI_MIN_IDLE}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT}
      max-lifetime: ${HIKARI_MAX_LIFETIME}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAILTRAP_USER}
    password: ${MAILTRAP_PASSWORD}
    properties:
      auth: true
      starttls:
        enable: true
        required: true
      ssl:
        trust: ${SSL_TRUST}

application:
  security:
    jwt:
      expiration: ${TOKEN_EXPIRATION}
  mailing:
    frontend:
      activation-url: ${ACTIVATION_URL}}

server:
  port: ${SERVER_PORT}
  servlet:
    session:
      timeout: 30m

logging:
  level:
    root: INFO

