spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travel_with_anna
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USER}
    password: ${MAILTRAP_PASSWORD}
    properties:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.mailtrap.io

application:
  security:
    jwt:
      expiration: 86400000 # a day
  mailing:
    frontend:
      activation-url: http://localhost:80/activate-account

server:
  port: 8080


