spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  flyway:
    baseline-on-migrate: true
    enabled: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAILTRAP_USER}
    password: ${MAILTRAP_PASSWORD}
    sender_email: ${MAILTRAP_USER}
    properties:
      auth: true
      starttls:
        enable: true
        required: true
      ssl:
        trust: ${MAILTRAP_SSL}

application:
  security:
    jwt:
      expiration: ${TOKEN_EXPIRATION}
    cors: ${CORS_ORIGIN}
  mailing:
    frontend:
      activation-url: ${ACTIVATION_URL}
      login-url: ${LOGIN_URL}

my_apis:
  country:
    country_url: ${API_COUNTRY}
  currency:
    currency_url: ${API_CURRENCY}
    header:
      apikey: ${API_CURRENCY_KEY}

server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 30m

logging:
  level:
    root: INFO

